#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'database',
  :git => 'git://github.com/SUSE-Cloud/cookbook-database.git'

cookbook 'mysql',
  :git => 'git://github.com/SUSE-Cloud/cookbook-mysql.git'

cookbook 'postgresql',
  :git => 'git://github.com/SUSE-Cloud/cookbook-postgresql.git'

cookbook 'chef-solo-search',
  :git => 'git://github.com/edelight/chef-solo-search.git'

cookbook 'rabbitmq-server',
  :git => 'git://github.com/att-cloud/cookbook-rabbitmq.git'

cookbook 'apache2',
  :git => 'git://github.com/SUSE-Cloud/cookbook-apache2.git'

cookbook 'memcached',
  :git => 'git://github.com/SUSE-Cloud/cookbook-memcached.git'

cookbook 'openstack-common',
  :git => 'git://github.com/stackforge/cookbook-openstack-common.git'

cookbook 'openstack-identity',
  :git => 'git://github.com/stackforge/cookbook-openstack-identity.git'

cookbook 'openstack-image',
  :git => 'git://github.com/stackforge/cookbook-openstack-image.git'

cookbook 'openstack-compute',
  :git => 'git://github.com/stackforge/cookbook-openstack-compute.git'

cookbook 'openstack-dashboard',
  :git => 'git://github.com/stackforge/cookbook-openstack-dashboard.git'

