#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'


cookbook 'memcached'

cookbook 'postgresql',
  :git => 'git://github.com/SUSE-Cloud/cookbook-postgresql.git'

cookbook 'chef-solo-search',
  :git => 'git://github.com/edelight/chef-solo-search.git'

cookbook 'rabbitmq-server',
  :git => 'git://github.com/att-cloud/cookbook-rabbitmq.git'

cookbook 'apache2',
  :git => 'git://github.com/SUSE-Cloud/cookbook-apache2.git'

cookbook 'openstack-ops-database',
  :git => 'git://github.com/stackforge/cookbook-openstack-ops-database.git'

cookbook 'openstack-common',
  :git => 'git://github.com/stackforge/cookbook-openstack-common.git'

cookbook 'openstack-identity',
  :git => 'git://github.com/stackforge/cookbook-openstack-identity.git'

cookbook 'openstack-image',
  :git => 'git://github.com/stackforge/cookbook-openstack-image.git'

cookbook 'openstack-compute',
  :git => 'git://github.com/stackforge/cookbook-openstack-compute.git'

cookbook 'openstack-dashboard',
  :git => 'git://github.com/stackforge/cookbook-openstack-dashboard.git'
cookbook 'openstack-block-storage',
  :git => 'git://github.com/stackforge/cookbook-openstack-block-storage.git'

cookbook 'openstack-network',
  :git => 'git://github.com/stackforge/cookbook-openstack-network.git'
