#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'database',
  :git => 'git://github.com/SUSE-Cloud/cookbook-database.git'

cookbook 'mysql',
  :git => 'git://github.com/SUSE-Cloud/cookbook-mysql.git'

cookbook 'postgresql',
  :git => 'git://github.com/SUSE-Cloud/cookbook-postgresql.git'

cookbook 'openstack-common',
  :git => 'git://github.com/SUSE-Cloud/cookbook-openstack-common.git'

cookbook 'chef-solo-search',
  :git => 'git://github.com/edelight/chef-solo-search.git'

cookbook 'rabbitmq-server',
  :git => 'git://github.com/SUSE-Cloud/cookbook-rabbitmq.git'

cookbook 'keystone',
  :git => 'git://github.com/SUSE-Cloud/cookbook-keystone.git'

cookbook 'glance',
  :git => 'git://github.com/SUSE-Cloud/cookbook-glance.git'

cookbook 'nova',
  :git => 'git://github.com/SUSE-Cloud/cookbook-nova.git'

cookbook 'apache2',
  :git => 'git://github.com/SUSE-Cloud/cookbook-apache2.git'

cookbook 'horizon',
  :git => 'git://github.com/SUSE-Cloud/cookbook-horizon.git'

cookbook 'memcached',
  :git => 'git://github.com/SUSE-Cloud/cookbook-memcached.git'
